name = "nav-dashboard"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Workers Sites - 静态文件托管
[site]
bucket = "./public"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "nav-dashboard-db"
database_id = "1ceb5072-5a0f-455c-8e31-bda626b8af67"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "KV"
id = "4de76a73c22f4185a3f532535594489e"
